service:
  name: user-storage
  image: quay.io/dborrego/user-storage
  version: latest

deployment:
  replicas: 2
  port: 8080
  health:
    liveness: /api/v1/health
    readiness: /api/v1/health
  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 32Mi

config:
  env:
