apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  source:
    path: dependencies/operator
    repoURL: "http://gogs.gogs.svc.cluster.local:3000/gogs/workshop-argocd.git"
    targetRevision: develop
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
